import { useEffect, useState } from "react";
import { Check, Clock3, FileAudio, MessageCircle, UploadCloud } from "lucide-react";
import { trpc } from "@/lib/trpc";

export function DeliveryPortalPanel() {
  const projectsQuery = trpc.studio.projects.useQuery(undefined, { retry: false });
  const projectId = projectsQuery.data?.[0]?.id;
  const deliveriesQuery = trpc.studio.deliveries.useQuery({ projectId: projectId || 0 }, { enabled: Boolean(projectId), retry: false });
  const commentMutation = trpc.studio.comment.useMutation();
  const createDeliveryMutation = trpc.studio.createDelivery.useMutation({ onSuccess: () => deliveriesQuery.refetch() });
  const approveMutation = trpc.studio.approveDelivery.useMutation({ onSuccess: () => deliveriesQuery.refetch() });
  const [selectedDeliveryId, setSelectedDeliveryId] = useState<number>();
  const [comment, setComment] = useState(""); const [approved, setApproved] = useState(false); const [fileName, setFileName] = useState("Nenhuma versão selecionada"); const [statusMessage, setStatusMessage] = useState(""); const [uploading, setUploading] = useState(false);
  const deliveries = deliveriesQuery.data || [];
  const selected = deliveries.find((delivery) => delivery.id === selectedDeliveryId) || deliveries[0];
  useEffect(() => { if (selected && selected.id !== selectedDeliveryId) setSelectedDeliveryId(selected.id); }, [selected, selectedDeliveryId]);
  useEffect(() => { if (selected) { setFileName(selected.fileName); setApproved(selected.status === "approved"); } }, [selected]);
  const addVersion = async (file?: File) => { if (!file || !projectId) return; setUploading(true); const nextVersion = deliveries.length + 1; try { const body = new FormData(); body.append("file", file); const response = await fetch(`http://127.0.0.1:8765/deliveries/upload?project_id=${projectId}&version=V${nextVersion.toString().padStart(2, "0")}`, { method: "POST", body }); if (!response.ok) throw new Error("upload"); const uploaded = await response.json() as { filePath?: string; url?: string }; createDeliveryMutation.mutate({ projectId, version: `V${nextVersion.toString().padStart(2, "0")}`, fileName: file.name, fileUrl: uploaded.filePath || uploaded.url }); setFileName(file.name); setStatusMessage("Nova versão persistida e pronta para revisão."); } catch { setStatusMessage("Não foi possível concluir o upload local."); } finally { setUploading(false); } };
  const timestampMs = 84000;
  return <section className="management-workspace"><div className="workspace-heading"><div><span className="panel-kicker">ENTREGAS · CLIENT PORTAL</span><h2>Revisões que deixam tudo claro</h2><p>Selecione uma versão persistida para comentar ou aprovar.</p></div><label className="secondary-button upload-button"><UploadCloud size={15} /> {uploading ? "Enviando..." : "Enviar versão"}<input type="file" accept="audio/*,.zip" onChange={(event) => void addVersion(event.target.files?.[0])} /></label></div><div className="delivery-focus"><div className="delivery-player"><div className="delivery-file"><FileAudio size={18} /><div><b>{selected?.fileName || fileName}</b><small>{selected ? `${selected.version} · ${selected.status}` : "Nenhuma entrega persistida"}</small></div></div><div className="delivery-wave">{Array.from({ length: 20 }, (_, index) => <i key={index} />)}</div><div className="delivery-time"><span>00:00</span><span>03:42</span></div></div><div className="delivery-comment-box"><div className="comment-label"><Clock3 size={14} /> Comentário por timestamp · 01:24</div><textarea value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Ex.: respirar um pouco mais antes do refrão..." /><div className="comment-actions"><button className="secondary-button" onClick={() => { if (selected && comment.trim()) { commentMutation.mutate({ deliveryId: selected.id, body: comment, timestampMs }); setStatusMessage("Comentário persistido na versão selecionada."); setComment(""); } }}><MessageCircle size={14} /> Adicionar comentário</button><button className="primary-button" onClick={() => { if (selected) { approveMutation.mutate({ deliveryId: selected.id }); setApproved(true); setStatusMessage("Versão aprovada e salva no histórico persistido."); } }} disabled={!selected}><Check size={14} /> {approved ? "Aprovado" : "Aprovar versão"}</button></div></div></div>{statusMessage && <div className="delivery-notice" role="status"><Check size={14} /> {statusMessage}</div>}<div className="delivery-history"><span className="panel-kicker">HISTÓRICO DE VERSÕES</span>{deliveries.length ? deliveries.map((item) => <button className="delivery-history-row" key={item.id} onClick={() => setSelectedDeliveryId(item.id)}><span className={item.id === selected?.id ? "version-dot active" : "version-dot"} /><b>{item.version}</b><span>{item.status === "approved" ? "Aprovado" : "Em revisão"}</span><small>{new Date(item.createdAt).toLocaleString("pt-BR")}</small></button>) : <div className="empty-state">Nenhuma versão persistida para este projeto.</div>}</div></section>;
}
