import { useEffect, useState } from "react";
import { FileSearch, Globe2, LockKeyhole, ShieldCheck, ExternalLink } from "lucide-react";
import { duckMasteringEssentials } from "../../../shared/pluginManifest";

type Report = { error?: string; name?: string; sha256?: string; static_audit?: string; manually_approved?: number; audit_report?: string };

export function PluginReportPanel() {
  const [report, setReport] = useState<Report | null>(null);
  const [reportId, setReportId] = useState<number>(() => Number(window.localStorage.getItem("duck-last-repo-report") || 1));
  const [sourceUrl, setSourceUrl] = useState("");
  const [auditState, setAuditState] = useState("");
  const load = (id = reportId) => fetch(`http://127.0.0.1:8765/repositories/reports/${id}`).then((response) => response.ok ? response.json() : null).then(setReport).catch(() => setReport(null));
  useEffect(() => { load(); }, [reportId]);
  const auditRepository = async () => { setAuditState("Auditando somente metadados..."); try { const response = await fetch("http://127.0.0.1:8765/repositories/audit", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ source_url: sourceUrl }) }); if (!response.ok) throw new Error("audit"); const result = await response.json(); setAuditState("Relatório salvo. Execução continua bloqueada."); setSourceUrl(""); setReportId(result.id); window.localStorage.setItem("duck-last-repo-report", String(result.id)); load(result.id); } catch { setAuditState("Backend local indisponível ou URL inválida."); } };
  return <section className="plugin-report panel"><div className="panel-heading"><div><span className="panel-kicker">PLUGIN VAULT · ASSET MANAGER</span><h2>Revisão antes de executar</h2></div><LockKeyhole size={18} className="panel-muted" /></div><p className="panel-description">O DuckOS diferencia manifesto, fonte oficial, licença, instalação detectada e aprovação. Nenhum binário proprietário é distribuído pelo pack.</p><div className="plugin-pack-manifest"><div className="panel-heading"><div><span className="panel-kicker">MANIFESTO · {duckMasteringEssentials.version}</span><h3>{duckMasteringEssentials.name}</h3></div><ShieldCheck size={17} /></div>{duckMasteringEssentials.items.map((item) => <article className="entity-row" key={item.productId}><div className="entity-main"><b>{item.name}</b><span>{item.category} · {item.formats.join(" / ")}</span><small>{item.note}</small></div><div className="entity-meta"><strong>{item.status}</strong><a href={item.officialUrl} target="_blank" rel="noreferrer" aria-label={`Abrir fonte oficial de ${item.name}`}><ExternalLink size={14} /></a></div></article>)}</div><div className="repo-audit-form"><Globe2 size={15} /><input value={sourceUrl} onChange={(event) => setSourceUrl(event.target.value)} placeholder="https://github.com/org/repo ou huggingface.co/..." /><button className="secondary-button" disabled={!sourceUrl.trim()} onClick={() => void auditRepository()}>Auditar URL</button></div>{auditState && <small className="audit-status" role="status">{auditState}</small>}{report && !report.error ? <div className="plugin-report-grid"><div><FileSearch size={20} /><b>{report.name || "Plugin inventariado"}</b><small>SHA-256: {(report.sha256 || "").slice(0, 22)}…</small></div><div><ShieldCheck size={20} /><b>{report.static_audit || "pending"}</b><small>{report.manually_approved ? "Aprovado manualmente" : "Execução bloqueada até aprovação manual"}</small></div></div> : <div className="queue-empty">Nenhum relatório local disponível ainda. Importe um VST/CLAP ou audite uma URL pública para gerar um relatório estático.</div>}</section>;
}
