import { BeatCard, beatCatalog } from "@/components/BeatCard";
import { StudioFooter, StudioNav } from "@/components/StudioNav";
import { Filter, Search, ShoppingBag } from "lucide-react";
import { useMemo, useState } from "react";

export default function Beats() {
  const [search, setSearch] = useState(""); const [mood, setMood] = useState("Todos"); const [genre, setGenre] = useState("Todos"); const [bpm, setBpm] = useState("Todos");
  const moods = ["Todos", ...Array.from(new Set(beatCatalog.map((beat) => beat.mood)))]; const genres = ["Todos", ...Array.from(new Set(beatCatalog.map((beat) => beat.genre)))];
  const filtered = useMemo(() => beatCatalog.filter((beat) => (mood === "Todos" || beat.mood === mood) && (genre === "Todos" || beat.genre === genre) && (bpm === "Todos" || (bpm === "<100" ? beat.bpm < 100 : beat.bpm >= 100)) && `${beat.name} ${beat.genre}`.toLowerCase().includes(search.toLowerCase())), [search, mood, genre, bpm]);
  return <div className="studio-page"><StudioNav /><main className="container pb-20 pt-14"><div className="max-w-3xl"><p className="eyebrow">LOJA DE BEATS · PRÉVIA</p><h1 className="mt-4 font-display text-5xl tracking-[-.05em] text-white md:text-6xl">Encontre a base.<br /><em className="text-emerald-300">Faça ela sua.</em></h1><p className="mt-6 max-w-xl text-sm leading-7 text-emerald-100/62">Filtre por energia, andamento ou gênero. Cada beat inclui uma prévia visual e licenças claras antes do checkout seguro.</p></div><div className="mt-12 grid gap-4 xl:grid-cols-[1fr_auto]"><div className="glass-panel flex items-center gap-3 px-4"><Search className="text-emerald-300" size={18} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por nome ou gênero" className="h-14 min-w-0 flex-1 bg-transparent text-sm text-white outline-none placeholder:text-emerald-100/35" /></div><div className="glass-panel flex items-center gap-3 px-5 text-xs text-emerald-100/65"><ShoppingBag size={17} className="text-emerald-300" /><span>Checkout seguro com Shopify</span><span className="rounded-full bg-amber-300/15 px-2 py-1 text-[.6rem] font-bold text-amber-200">PENDENTE</span></div></div><div className="mt-5 flex flex-wrap gap-3"><div className="filter-group"><Filter size={14} /><span>Clima</span>{moods.map((item) => <button key={item} onClick={() => setMood(item)} className={mood === item ? "filter-pill active" : "filter-pill"}>{item}</button>)}</div><div className="filter-group"><span>BPM</span>{["Todos", "<100", "100+"].map((item) => <button key={item} onClick={() => setBpm(item)} className={bpm === item ? "filter-pill active" : "filter-pill"}>{item}</button>)}</div><div className="filter-group"><span>Gênero</span><select value={genre} onChange={(event) => setGenre(event.target.value)} className="bg-transparent text-xs text-emerald-100 outline-none">{genres.map((item) => <option className="bg-emerald-950" key={item}>{item}</option>)}</select></div></div><div className="mt-9 flex items-center justify-between"><p className="text-sm text-emerald-100/55"><span className="font-bold text-white">{filtered.length}</span> beats disponíveis</p><span className="mono-label">AUDIÇÃO · CATÁLOGO</span></div><div className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map((beat) => <BeatCard beat={beat} key={beat.id} />)}</div>{filtered.length === 0 && <div className="glass-panel mt-5 p-10 text-center"><p className="text-lg font-bold text-white">Ainda não encontramos esse som.</p><p className="mt-2 text-sm text-emerald-100/55">Experimente remover um filtro ou use o Beat Lab para construir uma proposta guiada.</p></div>}</main><StudioFooter /></div>;
}
