import { PortalShell } from "@/components/PortalShell";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Blocks, LockKeyhole, ShieldAlert } from "lucide-react";

const statusCopy = { candidate: "Candidato", research_only: "Pesquisa", blocked: "Bloqueado", excluded: "Excluído" } as const;

export default function ExternalResources() {
  const { user } = useAuth(); const owner = user?.role === "admin"; const resources = trpc.owner.externalResources.useQuery(undefined, { enabled: owner });
  if (!owner) return <PortalShell label="Recursos externos"><section className="glass-panel max-w-xl p-8"><ShieldAlert className="text-amber-200" /><p className="eyebrow mt-5">ACESSO RESTRITO</p><h2 className="mt-2 text-2xl font-bold text-white">Somente o proprietário pode revisar integrações externas.</h2></section></PortalShell>;
  return <PortalShell label="Recursos externos"><section className="glass-panel p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">ADAPTADORES DESATIVADOS</p><h1 className="mt-2 font-display text-3xl text-white">Curadoria antes da conexão.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-emerald-100/60">Nenhum adaptador abaixo contém credencial, acessa conta bancária ou executa ação externa. Cada um requer aprovação do proprietário e sua própria validação antes da ativação.</p></div><Blocks className="text-emerald-300" /></div><div className="mt-7 grid gap-4 lg:grid-cols-2">{resources.data?.map((resource) => <article className="rounded-2xl border border-white/10 bg-black/15 p-5" key={resource.id}><div className="flex items-start justify-between gap-3"><div><p className="text-base font-bold text-white">{resource.name}</p><p className="mt-1 text-xs uppercase tracking-wider text-emerald-300">{resource.source} · {resource.activation}</p></div><span className={resource.status === "candidate" ? "status-chip chip-ready" : resource.status === "research_only" ? "status-chip chip-review" : "status-chip chip-progress"}>{statusCopy[resource.status]}</span></div><p className="mt-4 text-sm leading-6 text-emerald-100/60">{resource.purpose}</p><div className="mt-5 rounded-xl border border-white/10 bg-white/[.035] p-3"><p className="flex items-center gap-2 text-[.65rem] font-bold uppercase tracking-wider text-emerald-100/50"><LockKeyhole size={13} /> Ativação exigida</p><ul className="mt-2 space-y-1 text-xs leading-5 text-emerald-100/65">{resource.activationChecklist.map((item) => <li key={item}>• {item}</li>)}</ul></div></article>)}</div></section></PortalShell>;
}
