import { PortalShell } from "@/components/PortalShell";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { BadgeCheck, Download, FileKey2 } from "lucide-react";
import { toast } from "sonner";

export default function Licenses() {
  const licenses = trpc.portal.licenses.useQuery();
  const accessAsset = trpc.portal.licensedAssetUrl.useMutation({ onSuccess: ({ url, label }) => { window.open(url, "_blank", "noopener,noreferrer"); toast.success(`Acesso temporário liberado: ${label}`); }, onError: () => toast.error("Não foi possível validar o acesso a este ativo.") });
  return <PortalShell label="Minhas licenças"><section className="glass-panel p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">PROPRIEDADE & ACESSO</p><h1 className="mt-2 font-display text-3xl text-white">Licenças liberadas para você.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-emerald-100/60">Arquivos licenciados usam validação no servidor e URLs temporárias. Eles só aparecem após compra confirmada e associação pelo estúdio.</p></div><FileKey2 className="text-emerald-300" /></div><div className="mt-7 space-y-4">{licenses.isLoading ? <p className="text-sm text-emerald-100/55">Carregando licenças…</p> : licenses.data?.length ? licenses.data.map((license) => <article className="rounded-2xl border border-white/10 bg-black/15 p-5" key={license.id}><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><p className="text-lg font-bold text-white">{license.product?.name ?? "Produto associado"}</p><p className="mt-1 text-sm text-emerald-100/55">Licença {license.licenseNumber} · termos {license.termsVersion}</p></div><span className="status-chip chip-ready"><BadgeCheck size={13} /> {license.status}</span></div><div className="mt-5 border-t border-white/10 pt-4"><p className="field-label">Arquivos autorizados</p>{license.assets.length ? <div className="mt-3 space-y-2">{license.assets.map((asset) => <div className="flex items-center justify-between gap-3 rounded-xl bg-white/[.04] p-3" key={asset.id}><div><p className="text-sm font-semibold text-white">{asset.label}</p><p className="mt-1 text-xs text-emerald-100/50">{asset.version} · {asset.mimeType}</p></div><Button type="button" onClick={() => accessAsset.mutate({ licenseId: license.id, assetId: asset.id })} disabled={accessAsset.isPending} className="bg-white/10 text-white hover:bg-white/15"><Download size={15} /></Button></div>)}</div> : <p className="mt-2 text-xs text-emerald-100/45">Nenhum arquivo foi associado a esta licença.</p>}</div></article>) : <div className="rounded-2xl border border-dashed border-white/15 p-8 text-center"><FileKey2 className="mx-auto text-emerald-300" /><p className="mt-4 text-sm font-semibold text-white">Você ainda não possui licenças liberadas.</p><p className="mt-2 text-xs leading-5 text-emerald-100/50">O histórico aparece após uma compra confirmada por um provedor conectado.</p></div>}</div></section></PortalShell>;
}
