import { StudioFooter, StudioNav } from "@/components/StudioNav";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ShieldCheck } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

export default function Privacy() {
  const [request, setRequest] = useState({ email: "", requestType: "access" as "access" | "deletion" | "consent_withdrawal", privacyRegion: "BR" });
  const create = trpc.privacy.request.useMutation({ onSuccess: () => { toast.success("Solicitação registrada. A identidade será verificada antes de qualquer ação."); setRequest({ email: "", requestType: "access", privacyRegion: "BR" }); }, onError: () => toast.error("Não foi possível registrar a solicitação.") });
  const submit = (event: FormEvent) => { event.preventDefault(); create.mutate(request); };
  return <div className="studio-page min-h-screen"><StudioNav /><main className="container py-16"><section className="glass-panel mx-auto max-w-2xl p-7 md:p-10"><ShieldCheck className="text-emerald-300" /><p className="eyebrow mt-7">PRIVACIDADE & DADOS</p><h1 className="mt-3 font-display text-4xl text-white">Solicite acesso, exclusão ou retirada de consentimento.</h1><p className="mt-4 text-sm leading-7 text-emerald-100/60">Esta solicitação não altera dados automaticamente. Duck Studio deve confirmar sua identidade e avaliar a aplicabilidade da solicitação antes de executar qualquer exclusão ou disponibilizar informações.</p><form onSubmit={submit} className="mt-8 grid gap-4"><label><span className="field-label">E-mail relacionado ao pedido</span><input required type="email" value={request.email} onChange={(e) => setRequest({ ...request, email: e.target.value })} className="studio-input" placeholder="voce@email.com" /></label><label><span className="field-label">Solicitação</span><select value={request.requestType} onChange={(e) => setRequest({ ...request, requestType: e.target.value as typeof request.requestType })} className="studio-input"><option value="access">Acesso aos meus dados</option><option value="deletion">Exclusão de dados</option><option value="consent_withdrawal">Retirada de consentimento comercial</option></select></label><label><span className="field-label">Região</span><select value={request.privacyRegion} onChange={(e) => setRequest({ ...request, privacyRegion: e.target.value })} className="studio-input"><option value="BR">Brasil</option><option value="EU">União Europeia</option><option value="LATAM">América Latina</option><option value="other">Outra</option></select></label><Button type="submit" disabled={create.isPending} className="glow-button mt-2">{create.isPending ? "Registrando…" : "Registrar solicitação"}</Button></form></section></main><StudioFooter /></div>;
}
