import { PortalShell } from "@/components/PortalShell";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { MessageSquarePlus, ShieldAlert, UsersRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function CRM() {
  const { user } = useAuth(); const owner = user?.role === "admin"; const leads = trpc.owner.crmLeads.useQuery(undefined, { enabled: owner }); const utils = trpc.useUtils();
  const [drafts, setDrafts] = useState<Record<number, string>>({});
  const updateStatus = trpc.owner.updateLeadStatus.useMutation({ onSuccess: () => { utils.owner.crmLeads.invalidate(); toast.success("Status atualizado."); }, onError: () => toast.error("Não foi possível atualizar o status.") });
  const addNote = trpc.owner.addLeadNote.useMutation({ onSuccess: (_result, input) => { setDrafts({ ...drafts, [input.leadId]: "" }); utils.owner.crmLeads.invalidate(); toast.success("Nota interna registrada."); }, onError: () => toast.error("Não foi possível registrar a nota.") });
  if (!owner) return <PortalShell label="CRM"><section className="glass-panel max-w-xl p-8"><ShieldAlert className="text-amber-200" /><p className="eyebrow mt-5">ACESSO RESTRITO</p><h2 className="mt-2 text-2xl font-bold text-white">O CRM é exclusivo do proprietário.</h2></section></PortalShell>;
  return <PortalShell label="CRM leve"><section className="glass-panel p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">LEADS E RELACIONAMENTO</p><h1 className="mt-2 font-display text-3xl text-white">Contexto real antes do próximo passo.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-emerald-100/60">Interesses são derivados do serviço solicitado; notas são internas. Não há segmentação automática, contato externo ou dados inventados.</p></div><UsersRound className="text-emerald-300" /></div><div className="mt-7 space-y-4">{leads.data?.length ? leads.data.map((lead) => <article className="rounded-2xl border border-white/10 bg-black/15 p-5" key={lead.id}><div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><p className="text-base font-bold text-white">{lead.name}</p><p className="mt-1 text-sm text-emerald-100/60">{lead.email}</p><div className="mt-3 flex flex-wrap gap-2"><span className="status-chip chip-review">Interesse: {lead.service}</span><span className="status-chip chip-ready">Origem: {lead.source}</span>{lead.marketingConsent && <span className="status-chip chip-progress">Consentimento comercial</span>}</div></div><label><span className="field-label">Status</span><select value={lead.status} onChange={(event) => updateStatus.mutate({ leadId: lead.id, status: event.target.value as "new" | "qualified" | "active" | "closed" })} disabled={updateStatus.isPending} className="studio-input min-w-36"><option value="new">Novo</option><option value="qualified">Qualificado</option><option value="active">Ativo</option><option value="closed">Encerrado</option></select></label></div><p className="mt-4 rounded-xl bg-white/[.035] p-3 text-sm leading-6 text-emerald-100/65">{lead.message || "Sem contexto adicional informado."}</p><div className="mt-4 border-t border-white/10 pt-4"><p className="field-label">Notas internas</p>{lead.notes.length ? <div className="mt-2 space-y-2">{lead.notes.map((note) => <p className="rounded-xl bg-white/[.045] p-3 text-xs leading-5 text-emerald-100/65" key={note.id}>{note.note}</p>)}</div> : <p className="mt-2 text-xs text-emerald-100/45">Ainda não há notas internas.</p>}<div className="mt-3 flex gap-2"><input value={drafts[lead.id] ?? ""} onChange={(event) => setDrafts({ ...drafts, [lead.id]: event.target.value })} className="studio-input min-w-0 py-2 text-sm" placeholder="Adicionar nota interna" /><Button type="button" disabled={addNote.isPending || !(drafts[lead.id] ?? "").trim()} onClick={() => addNote.mutate({ leadId: lead.id, note: drafts[lead.id] ?? "" })} className="bg-white/10 text-white hover:bg-white/15"><MessageSquarePlus size={16} /></Button></div></div></article>) : <div className="rounded-2xl border border-dashed border-white/15 p-8 text-center text-sm text-emerald-100/50">Não há leads captados ainda. O CRM exibirá somente formulários reais enviados pela plataforma.</div>}</div></section></PortalShell>;
}
