import { PortalShell } from "@/components/PortalShell";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { ShieldAlert, UserCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function PrivacyControl() {
  const { user } = useAuth(); const isOwner = user?.role === "admin";
  const requests = trpc.owner.privacyRequests.useQuery(undefined, { enabled: isOwner }); const utils = trpc.useUtils();
  const [verified, setVerified] = useState<Record<number, boolean>>({});
  const process = trpc.owner.processPrivacyRequest.useMutation({ onSuccess: (result) => { if (result.exportData) { const blob = new Blob([JSON.stringify(result.exportData, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `duck-privacidade-${Date.now()}.json`; link.click(); URL.revokeObjectURL(url); } utils.owner.privacyRequests.invalidate(); toast.success(result.status === "completed" ? result.exportData ? "Solicitação processada e exportação baixada." : "Solicitação processada e auditada." : "Solicitação marcada para verificação de identidade."); }, onError: () => toast.error("Não foi possível processar a solicitação.") });
  if (!isOwner) return <PortalShell label="Privacidade"><section className="glass-panel max-w-xl p-8"><ShieldAlert className="text-amber-200" /><p className="eyebrow mt-5">ACESSO RESTRITO</p><h2 className="mt-2 text-2xl font-bold text-white">Somente o proprietário pode processar dados de titulares.</h2></section></PortalShell>;
  return <PortalShell label="Privacidade & titulares"><section className="glass-panel p-6"><p className="eyebrow">FILA DE SOLICITAÇÕES</p><h1 className="mt-2 font-display text-3xl text-white">Processamento com confirmação humana.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-emerald-100/60">Confirme a identidade por um canal adequado antes de selecionar a opção abaixo. Acesso, retirada de consentimento e exclusão de leads ficam registrados na trilha de auditoria.</p><div className="mt-7 space-y-3">{requests.data?.length ? requests.data.map((request) => <article className="rounded-2xl border border-white/10 bg-black/15 p-4" key={request.id}><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-sm font-semibold text-white">{request.email}</p><p className="mt-1 text-xs text-emerald-100/50">{request.requestType} · {request.privacyRegion} · {new Date(request.createdAt).toLocaleDateString("pt-BR")}</p></div><span className="status-chip chip-review">{request.status}</span></div>{request.status !== "completed" && <div className="mt-4 flex flex-wrap items-center gap-3"><label className="flex items-center gap-2 text-xs text-emerald-100/65"><input type="checkbox" checked={verified[request.id] ?? false} onChange={(event) => setVerified({ ...verified, [request.id]: event.target.checked })} className="h-4 w-4 accent-emerald-300" />Identidade confirmada manualmente</label><Button type="button" onClick={() => process.mutate({ requestId: request.id, identityVerified: verified[request.id] ?? false })} disabled={process.isPending} className="bg-white/10 text-white hover:bg-white/15">{verified[request.id] ? "Processar solicitação" : "Solicitar verificação"}<UserCheck size={15} /></Button></div>}</article>) : <p className="rounded-2xl border border-dashed border-white/15 p-5 text-sm text-emerald-100/50">Não há solicitações registradas.</p>}</div></section></PortalShell>;
}
