import { trpc } from "@/lib/trpc";
import { Filter, Search, ShieldCheck } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

type Locale = "es" | "en";
const text = {
  es: { home: "Inicio", title: "Catálogo de beats", intro: "Explora disponibilidad real publicada por el estudio. El checkout se activa solo cuando el proveedor esté conectado.", search: "Buscar producto", noProducts: "No hay productos publicados todavía.", privacy: "Privacidad", privacyTitle: "Solicitar acceso o eliminación de datos", email: "Correo electrónico", request: "Solicitud", submit: "Registrar solicitud", access: "Acceso a mis datos", deletion: "Eliminación de datos", withdrawal: "Retirar consentimiento comercial", received: "Solicitud registrada. La identidad se verificará antes de cualquier acción." },
  en: { home: "Home", title: "Beat catalog", intro: "Browse real availability published by the studio. Checkout activates only when the provider is connected.", search: "Search product", noProducts: "No products are published yet.", privacy: "Privacy", privacyTitle: "Request data access or deletion", email: "Email address", request: "Request", submit: "Submit request", access: "Access my data", deletion: "Delete my data", withdrawal: "Withdraw marketing consent", received: "Request recorded. Identity will be verified before any action." },
} as const;

function Header({ locale }: { locale: Locale }) { return <header className="studio-header"><div className="container flex h-20 items-center justify-between"><Link href={`/${locale}`} className="brand-mark"><span className="brand-dot" /><span>DUCK</span><small>STUDIO</small></Link><div className="flex items-center gap-3 text-xs font-bold"><Link href="/" className="text-emerald-100/60 hover:text-white">PT</Link><Link href="/es" className={locale === "es" ? "rounded-full bg-emerald-300 px-2 py-1 text-emerald-950" : "text-emerald-100/60 hover:text-white"}>ES</Link><Link href="/en" className={locale === "en" ? "rounded-full bg-emerald-300 px-2 py-1 text-emerald-950" : "text-emerald-100/60 hover:text-white"}>EN</Link></div></div></header>; }
function LocaleFooter({ locale }: { locale: Locale }) { const copy = locale === "es" ? { description: "Producción, beats y dirección sonora. Cada entrega empieza con intención.", catalog: "Beats", privacy: "Privacidad" } : { description: "Production, beats and sonic direction. Every delivery starts with intention.", catalog: "Beats", privacy: "Privacy" }; return <footer className="border-t border-white/10 bg-[#03130f] py-10"><div className="container flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div><div className="brand-mark mb-3"><span className="brand-dot" /><span>DUCK</span><small>STUDIO</small></div><p className="max-w-sm text-sm leading-6 text-emerald-100/55">{copy.description}</p></div><div className="flex gap-6 text-sm text-emerald-100/65"><Link href={`/${locale}/beats`} className="hover:text-white">{copy.catalog}</Link><Link href={`/${locale}/privacy`} className="hover:text-white">{copy.privacy}</Link></div></div></footer>; }

export function SpanishBeats() { return <LocaleBeats locale="es" />; }
export function EnglishBeats() { return <LocaleBeats locale="en" />; }
export function SpanishPrivacy() { return <LocalePrivacy locale="es" />; }
export function EnglishPrivacy() { return <LocalePrivacy locale="en" />; }

function LocaleBeats({ locale }: { locale: Locale }) {
  const t = text[locale]; const [search, setSearch] = useState(""); const products = trpc.catalog.list.useQuery();
  const visible = useMemo(() => products.data?.filter((item) => `${item.name} ${item.description ?? ""} ${item.category}`.toLowerCase().includes(search.toLowerCase())) ?? [], [products.data, search]);
  return <div className="studio-page min-h-screen"><Header locale={locale} /><main className="container pb-20 pt-14"><p className="eyebrow">DUCK STUDIO</p><h1 className="mt-3 font-display text-5xl text-white">{t.title}</h1><p className="mt-4 max-w-xl text-sm leading-7 text-emerald-100/60">{t.intro}</p><div className="glass-panel mt-8 flex items-center gap-3 px-4"><Search className="text-emerald-300" size={18} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={t.search} className="h-14 min-w-0 flex-1 bg-transparent text-sm text-white outline-none placeholder:text-emerald-100/35" /></div><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map((product) => <article className="glass-panel p-5" key={product.id}><p className="mono-label">{product.category}</p><h2 className="mt-3 text-xl font-bold text-white">{product.name}</h2><p className="mt-2 min-h-10 text-sm leading-6 text-emerald-100/55">{product.description}</p><div className="mt-6 flex items-center justify-between border-t border-white/10 pt-4"><span className="text-sm font-bold text-emerald-300">{product.priceCents === null ? "—" : new Intl.NumberFormat(locale === "es" ? "es-BR" : "en-US", { style: "currency", currency: product.currency }).format(product.priceCents / 100)}</span><span className="status-chip chip-review">{product.availability}</span></div></article>)}</div>{!products.isLoading && visible.length === 0 && <div className="glass-panel mt-5 p-10 text-center"><Filter className="mx-auto text-emerald-300" /><p className="mt-4 text-sm text-emerald-100/60">{t.noProducts}</p></div>}</main><LocaleFooter locale={locale} /></div>;
}

function LocalePrivacy({ locale }: { locale: Locale }) {
  const t = text[locale]; const [form, setForm] = useState({ email: "", requestType: "access" as "access" | "deletion" | "consent_withdrawal", privacyRegion: locale === "es" ? "LATAM" : "other" });
  const request = trpc.privacy.request.useMutation({ onSuccess: () => { toast.success(t.received); setForm({ ...form, email: "" }); }, onError: () => toast.error("Request could not be recorded.") }); const submit = (event: FormEvent) => { event.preventDefault(); request.mutate(form); };
  return <div className="studio-page min-h-screen"><Header locale={locale} /><main className="container py-16"><section className="glass-panel mx-auto max-w-2xl p-8"><ShieldCheck className="text-emerald-300" /><p className="eyebrow mt-7">{t.privacy.toUpperCase()}</p><h1 className="mt-3 font-display text-4xl text-white">{t.privacyTitle}</h1><form onSubmit={submit} className="mt-8 grid gap-4"><label><span className="field-label">{t.email}</span><input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className="studio-input" /></label><label><span className="field-label">{t.request}</span><select value={form.requestType} onChange={(event) => setForm({ ...form, requestType: event.target.value as typeof form.requestType })} className="studio-input"><option value="access">{t.access}</option><option value="deletion">{t.deletion}</option><option value="consent_withdrawal">{t.withdrawal}</option></select></label><button disabled={request.isPending} className="glow-button mt-2">{t.submit}</button></form></section></main><LocaleFooter locale={locale} /></div>;
}
